import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { db } from "@/lib/db";

/**
 * Server-side Better Auth configuration.
 *
 * Auth models (User, Session, Account, Verification) are generated by
 * `npx @better-auth/cli generate` and live in prisma/schema.prisma.
 *
 * IMPORTANT: Never log passwords, tokens, or session values.
 */
export const auth = betterAuth({
  database: drizzleAdapter(db, { provider: "pg" }),
  secret: process.env.BETTER_AUTH_SECRET,
  trustedOrigins: [
    process.env.NEXT_PUBLIC_APP_URL as string,
    process.env.BETTER_AUTH_URL as string,
    "http://localhost:3000",
    "https://podcasts-ai-app.vercel.app"
  ].filter(Boolean),

  socialProviders: {
    google: {
      clientId: process.env.GOOGLE_CLIENT_ID!,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
    },
    github: {
      clientId: process.env.GITHUB_CLIENT_ID!,
      clientSecret: process.env.GITHUB_CLIENT_SECRET!,
    },
  },

  emailAndPassword: {
    enabled: true,
    autoSignIn: true,
  },

  emailVerification: {
    sendOnSignUp: true,
    sendVerificationEmail: async ({ user, url }) => {
      // TODO: Replace with Resend/SendGrid in production
      console.log(`[Auth] Verify email for ${user.email}: ${url}`);
    },
  },

  user: {
    deleteUser: {
      enabled: true,
    },
  },

  advanced: {
    cookiePrefix: "podcast_app",
  },
});

export type Session = typeof auth.$Infer.Session;
